model = "gpt-5-codex"
model_reasoning_effort = "high"


network_access = true

[tools]
web_search = true


[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@latest"]

# 環境変数として API キーを渡す（こっちの方が確実）
env = { CONTEXT7_API_KEY = "${CONTEXT7_API_KEY}" }
